spring:
  # Database
  datasource:
    url: jdbc:postgresql://localhost:5432/credit_bpmn?currentSchema=credit_bpmn
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
  jms:
    pub-sub-domain: true
  # Active MQ
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: true
camunda.bpm:
  admin-user:
    id: admin
    password: admin
    firstName: Roman
    lastName: Maniev
  filter:
    create: All Tasks
#  default-serialization-format: application/json
server:
  port: 8080
  error:
    whitelabel:
      enabled: false
url:
  authentication-service: http://localhost:8081/mockAuthenticate/authenticate
  customer-financial-data-service: http://localhost:8081/mockAuthenticate/customerFinancialData
  validate-credit-request: http://localhost:8081/mockAuthenticate/validateCreditRequest
  create-new-contract: http://localhost:8081/mockAuthenticate/createNewContract
  update-contract: http://localhost:8081/mockAuthenticate/updateContract
queue:
  contract: contract.queue